-- MySQL Script generated by MySQL Workbench
-- Mon 25 Feb 2019 11:38:06 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bankdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bankdb` ;

-- -----------------------------------------------------
-- Schema bankdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bankdb` DEFAULT CHARACTER SET utf8 ;
USE `bankdb` ;

-- -----------------------------------------------------
-- Table `bankdb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`Department` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`Department` (
  `idDepartment` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `contacts` VARCHAR(45) NULL,
  `idSchedule` INT,
    PRIMARY KEY (`idDepartment`),
      INDEX `fk_Department_Schedule_idx` (`idSchedule` ASC),
	CONSTRAINT `fk_Department_Schedule`
    FOREIGN KEY (`idSchedule`)
    REFERENCES `bankdb`.`Schedule` (`idSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bankdb`.`Schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`Schedule` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`Schedule` (
  `idSchedule` INT NOT NULL AUTO_INCREMENT,
  `mon` VARCHAR(45) NULL,
  `tue` VARCHAR(45) NULL,
  `wed` VARCHAR(45) NULL,
  `thu` VARCHAR(45) NULL,
  `fri` VARCHAR(45) NULL,
  `sat` VARCHAR(45) NULL,
  `sun` VARCHAR(45) NULL,
  PRIMARY KEY (`idSchedule`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`Client` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `typeClient` VARCHAR(45) NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`PersonClient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`PersonClient` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`PersonClient` (
  `idPersonClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `passport` VARCHAR(45) NULL,
  `idClient` INT NULL,
  PRIMARY KEY (`idPersonClient`),
  INDEX `fk_PersonClient_Client_idx` (`idClient` ASC),
  CONSTRAINT `fk_PersonClient_Client`
    FOREIGN KEY (`idClient`)
    REFERENCES `bankdb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`EntityClient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`EntityClient` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`EntityClient` (
  `idEntityClient` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `kind` VARCHAR(45) NULL,
  `manager` VARCHAR(45) NULL,
  `idClient` INT NULL,
  PRIMARY KEY (`idEntityClient`),
  INDEX `fk_EntityClient_Client_idx` (`idClient` ASC),
  CONSTRAINT `fk_EntityClient_Client`
    FOREIGN KEY (`idClient`)
    REFERENCES `bankdb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`ContactPerson`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`ContactPerson` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`ContactPerson` (
  `idContactPerson` INT NOT NULL AUTO_INCREMENT,
  `idEntityClient` INT NULL,
  `name` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idContactPerson`),
  INDEX `fk_ContactPerson_Client_idx` (`idEntityClient` ASC),
  CONSTRAINT `fk_ContactPerson_Client`
    FOREIGN KEY (`idEntityClient`)
    REFERENCES `bankdb`.`EntityClient` (`idEntityClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`AccountType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`AccountType` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`AccountType` (
  `idAccountType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `maxCredit` INT NULL,
  `interestOnLoan` INT NULL,
  `minPeriod` INT NULL,
  `maxPeriod` INT NULL,
  `interestOnDeposit` INT NULL,
  `minDepositSum` INT NULL,
  `maxAssessment` INT NULL,
  `maxCancellation` INT NULL,
  PRIMARY KEY (`idAccountType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`Account` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`Account` (
  `idAccount` INT NOT NULL AUTO_INCREMENT,
  `idDepartment` INT NOT NULL,
  `accountNum`  INT NOT NULL,
  `idClient` INT NOT NULL,
  `idType` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  `debit` DOUBLE NULL,
  `credit` DOUBLE NULL,
  `deposit` DOUBLE NULL,
  `balance` DOUBLE NULL,
  `period` INT NULL,
  `openDate` DATE NULL,
  `closeDate` DATE NULL,
  PRIMARY KEY (`idAccount`),
  INDEX `fk_Account_Client_idx` (`idClient` ASC),
  INDEX `fk_Account_Type_idx` (`idType` ASC),
  INDEX `fk_Account_Department_idx` (`idDepartment` ASC),
  CONSTRAINT `fk_Account_Client`
    FOREIGN KEY (`idClient`)
    REFERENCES `bankdb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Department`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `bankdb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Account_Type`
    FOREIGN KEY (`idType`)
    REFERENCES `bankdb`.`AccountType` (`idAccountType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bankdb`.`Operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bankdb`.`Operation` ;

CREATE TABLE IF NOT EXISTS `bankdb`.`Operation` (
  `idOperation` INT NOT NULL AUTO_INCREMENT,
  `idAccount` INT NOT NULL,
  `sum` DOUBLE NULL,
  `time` TIMESTAMP NULL,
  `idDepartment` INT NULL,
  PRIMARY KEY (`idOperation`),
  INDEX `fk_Operation_Account_idx` (`idAccount` ASC),
  INDEX `fk_Operation_Department_idx` (`idDepartment` ASC),
  CONSTRAINT `fk_Operation_Account`
    FOREIGN KEY (`idAccount`)
    REFERENCES `bankdb`.`Account` (`idAccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Operation_Department`
    FOREIGN KEY (`idDepartment`)
    REFERENCES `bankdb`.`Department` (`idDepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
